Footer, HTML semantic elements, new photos
openeew/openeew.com pull request #34
Opened 2021-05-27 20:06 UTC by rdkelley

2021-05-27 20:41 UTC, krook commented on src/content/en.json
> +  "copyrightInfo": "For trademark usage guidelines, privacy and cookie policies, and other applicable policies, as well as terms and conditions governing this web site, please see www.lfprojects.org.
My only nit here is the mixing of camelCase with underscores.

2021-05-27 20:42 UTC, krook requested changes
I just had a nit about camel case and underscores in the i18n file.

2021-05-28 00:07 UTC, rdkelley commented
Oh, good catch. I'm not sure if there is some standard for those documents, so I'll go with camel case since that's what we use elsewhere. Just pushed up a fix!

2021-05-28 12:35 UTC, krook approved these changes

2021-05-28 12:36 UTC, merged